title: Navigation
label: Navigation
preview: '@preview--blocks'

context:
  component-type: block

variants:
  - name: default
    hidden: true

  - name: global
    context:
      classModifier: global
      navigation:
        - text: services
          url: JavaScript:Void(0);
        - text: research
          url: JavaScript:Void(0);
        - text: training
          url: JavaScript:Void(0);
        - text: about us
          url: JavaScript:Void(0);

  - name: main
    context:
      classModifier: main
      navigation:
        - text: Home
          url: JavaScript:Void(0);
        - text: Download
          url: JavaScript:Void(0);
        - text: Release Notes
          url: JavaScript:Void(0);
        - text: FAQ
          url: JavaScript:Void(0);
        - text: Help
          url: JavaScript:Void(0);
        - text: Licence
          url: JavaScript:Void(0);
        - text: About
          url: JavaScript:Void(0);
        - text: Feedback
          url: JavaScript:Void(0);

  - name: additional
    context:
      heading: European Bioinformatics Institute
      classModifier: additional
      title: European Bioinformatics Institute
      navigation:
        - text: services
          url: JavaScript:Void(0);
        - text: research
          url: JavaScript:Void(0);
        - text: training
          url: JavaScript:Void(0);
        - text: about us
          url: JavaScript:Void(0);
