title: Visual Framework Link
label: Link
status: live
collated: true
preview: '@preview--nogrid'
context:
  component-type: element
variants:
  - name: default
    hidden: true;
    context:
      link_href: "JavaScript:Void(0);"
      text: "A default link"
