version: 1
snapshot:
  widths: [375, 800, 1330]
static-snapshots:
  base-url: /
  snapshot-files: 'build/components/preview/**/*,html'
  ignore-files: 'embl-breadcrumbs-lookup.html, embl-boilerplate-page.html, embl-conditional-edit.html, /embl-content-hub-loader.html, embl-content-meta-properties.html, embl-grid.html, embl-group-page--contact.html, embl-group-page--default.html, embl-group-page.html, embl-subsite-page.html, _previews/*.html, vf-boilerplate-page.html, vf-deprecated.html, vf-grid-page.html, vf-grid.html, vf-heading--default.html, vf-no-js.html, vf-pagination--compact.html, vf-pagination--compact.html, vf-pagination.html'
