# Deploy the pattern library to gh-pages
language: node_js
node_js:
  - 10

stages:
  - deploy

deploy:
  # tags:
  #   - docker
  # before_script:
  #   - add-ssh-key ${SSH_OWNER_ID} "${SSH_OWNER_KEY}" ${SSH_APACHE_ID} "${SSH_APACHE_KEY}"
  script:
    - npm install
    - npm install -g gulp-cli
    - gulp build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  target-branch: gh-pages
  local-dir: build
  cache:
    paths:
      - node_modules
  on:
    branch:
      - develop
      - "gh-pages-ci"
  except:
    - /^.visual-framework\/.*$/
