title: Breadcrumbs
label: Breadcrumbs
status: beta
context:
  component-type: block
  breadcrumbs:
    - text: Explore
      url: JavaScript:Void(0);
    - text: Topics
      url: JavaScript:Void(0);
    - text: Centre
  related:
    - text: Biscuits
      url: JavaScript:Void(0);
    - text: Fruits For Cheese
      url: JavaScript:Void(0);
