title: Breadcrumbs
label: Breadcrumbs
preview: '@preview--blocks'
context:
  component-type: block

  breadcrumbs:
    - text: Explore
      url: JavaScript:Void(0);
    - text: Topics
      url: JavaScript:Void(0);
    - text: Centre
