title: Masthead
label: Masthead
preview: '@preview--nogrid'
context:
  component-type: block

  masthead_href: 'JavaScript:Void(0);'

  seacrch_example_href_1: 'JavaScript:Void(0);'
  seacrch_example_href_2: 'JavaScript:Void(0);'
  seacrch_example_href_3: 'JavaScript:Void(0);'
