title: Masthead
label: Masthead
preview: '@preview--nogrid'
context:
  component-type: block

  masthead__link: 'JavaScript:Void(0);'

  seacrch_example_1: 'JavaScript:Void(0);'
  seacrch_example_2: 'JavaScript:Void(0);'
  seacrch_example_3: 'JavaScript:Void(0);'
