# The title shown on the component page
title: EMBL Logo
# Label shown on index pages
label: EMBL Logo
status: alpha
# The template used from /components/_previews
#
# Per-variant options
variants:
  - name: responsive
    hidden: true
    context:
      deprecated_text: "'@embl-logo--responsive' is deprecated, use '@embl-logo'"
context:
  # custom-values: passed as {{custom-values}}
  component-type: embl-element
  href: http://www.embl.de
  logo_text: European Molecular Biology Laboratory Home
  # image: ../../assets/vf-component-name/assets/vf-component-name.png
  # - note on paths: be sure to prefix with `../../`
  # - Why? https://github.com/visual-framework/vf-core/issues/364
