title: Section Header
label: Section Header
status: live
context:
  component-type: block
  section_title: Projects
variants:
  - name: default
  - name: is-link
    context:
      href: hello
  - name: has-sub-heading
    context:
      section__subheading: News from EMBL’s six sites
