title: Section Header
label: Section Header
status: live
context:
  component-type: block
  section_title: Projects
variants:
  - name: default
    title: Default
  - name: is a link
    title: Is a link
    context:
      href: JavaScript:Void(0);
  - name: has a sub-heading
    title: Has a sub-heading
    context:
      section__subheading: News from EMBL’s six sites
  - name: has a sub-heading and link
    title: Has a sub-heading and link
    context:
      href: JavaScript:Void(0);
      section__subheading: News from EMBL’s six sites
