title: Section Header
label: Section Header
status: live
context:
  component-type: block
  section_title: Projects
variants:
  - name: default
  - name: is a link
    context:
      href: hello
  - name: has a sub-heading
    context:
      section__subheading: News from EMBL’s six sites
  - name: has a sub-heading and link
    context:
      href: hello
      section__subheading: News from EMBL’s six sites
