# The title shown on the component page
title: Search
# Label shown on index pages
label: Search
status: alpha
collated: true
# The template used from /components/_previews
# preview: '@preview--blocks'
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
context:
  component-type: block
  # custom-values: passed as {{custom-values}}

  label: Search
  button: Search
