title: Visual Framework Headings
label: Headings
preview: '@preview--elements'
status: beta
context:
  pattern-type: element
  vf-heading-modifiers:
    display:
      title: This heading size is display and inverted
      element: h1
      modifiers: -xl vf-text--invert
    extra-large:
      title: This heading size is extra large
      element: h2
      modifiers:  -xl
    large:
      title: This heading size is large
      element: h3
      modifiers:  -l
    regular:
      title: This heading size is regular
      element: h4
      modifiers:  -r
    small:
      title: This heading size is small
      element: h5
      modifiers:  -s
