title: Visual Framework Headings
label: Headings
preview: '@preview--elements'
status: beta
variants:
  - name: template
    hidden: true
context:
  pattern-type: element
  vf-heading-modifiers:
    - display: true
      title: This heading size is display and inverted
    - extra-large: true
      title: This heading size is extra large
    - large: true
      title: This heading size is large
    - regular: true
      title: This heading size is regular
    - small: true
      title: This heading size is small
