title: Logo
label: Logo

context:
  component-type: element

  href: http://www.embl.de
  logo_text: Visual Framework 2.0

variants:
  - name: default
    context:
      image: '/assets/vf-logo/assets/logo.png'
  - name: responsive
    context:
      responsive: true
      image: '/assets/vf-logo/assets/logo.svg'
  - name: hidden text
    context:
      image: '/assets/vf-logo/assets/logo.png'
      hidden: true
