# The title shown on the component page
title: Card Container
# Label shown on index pages
label: Card Container
status: alpha
preview: '@preview--nogrid'
collated: true
# The template used from /components/_previews
#
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
context:
  component-type: container
  section_title: Cards
  section__subheading: To promote molecular biology across Europe
  vf_cards:
    - card_title: A Easy Card Title 1
      card_href: http://www.hello.com
      modifier: vf-card--easy
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
    - card_title: A Normal Card Title 1
      card_href: http://www.hello.com
      modifier: vf-card--normal
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
    - card_title: A Normal Card Title 1.5
      card_href: http://www.hello.com
      modifier: vf-card--normal vf-card-theme--primary
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
    - modifier: vf-card--normal vf-card-theme--secondary
      card_title: A Normal Card Title 2
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
    - modifier: vf-card--normal vf-card-theme--tertiary
      card_title: A Normal Card Title 3
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
    - modifier: vf-card--normal vf-card-theme--quaternary
      card_title: A Normal Card Title 4
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
    - card_title: A Medium Card Title 1
      card_href: http://www.hello.com
      modifier: vf-card--medium
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
    - card_title: A Medium Card Title 1.5
      card_href: http://www.hello.com
      modifier: vf-card--medium vf-card-theme--primary
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
    - modifier: vf-card--medium vf-card-theme--secondary
      card_title: A Medium Card Title 2
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
    - modifier: vf-card--medium vf-card-theme--tertiary
      card_title: A Medium Card Title 3
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
    - modifier: vf-card--medium vf-card-theme--quaternary
      card_title: A Medium Card Title 4
      card_image: ../../assets/vf-card/assets/vf-card-example.png
      card_text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  # custom-values: passed as {{custom-values}}
  # title: Title text
  # text: String of text
  # image: ../../assets/vf-component-name/assets/vf-component-name.png
  # - note on paths: be sure to prefix with `../../`
  # - Why? https://github.com/visual-framework/vf-core/issues/364
