title: Visual Framework Lists
label: Lists
preview: '@preview--elements'
status: alpha
variants:
  - name: default
    label: Block
    title: "vf-list component: Block"
context:
  component-type: element
