title: Button
label: Button
status: beta
collated: true
variants:
  - name: default
    hidden: true
  - name: examples
    hidden: false
  - name: outline
    hidden: true
  - name: sizes
    hidden: true
  - name: styles
    hidden: true
  - name: variants
    hidden: true
