title: Banner
label: Banner
variants:
    name: default
    hidden: true
context:
  pattern-type: container
  data-service-id: MyService
  data-protection-version: 0.1
  vf-data-protection-banner__text:
  vf-data-protection-banner__link: I agree, dismiss this banner
