title: Banner
label: Banner

context:
  component-type: container
  data-service-id: MyService
  data-protection-version: 0.1
  vf-data-protection-banner__text: I agree, dismiss this banner
  vf-data-protection-banner__link:
variants:
  - name: default
    hidden: true
