# The title shown on the component page
title: Card
# Label shown on index pages
label: Card
status: live
# The template used from /components/_previews

context:
  component-type: block
  # custom-values: passed as {{custom-values}}

  title: Title Block
  text: two lines of text
  image: ../../assets/vf-card/assets/vf-card-example.png

variants:
  - name: default
    label: Easy
    context:
      modifier: vf-card--easy
      title: An Easy Card Title
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: normal
    context:
      modifier: vf-card--normal
      title: A Normal Card Title
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: medium
    context:
      modifier: vf-card--medium
      title: A Medium Card Title
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: hard
    context:
      modifier: vf-card--hard 
      title: An Hard Card Title
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: extreme
    hidden: true
    context:
      modifier: vf-card--extreme
      title: An Extreme Card Title
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: intense
    hidden: true
    context:
      modifier: vf-card--intense
      title: An Intense Card Title
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
  - name: as-link
    context:
      title: A Card Is A Link Title
      text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum, omnis provident saepe aut eius aliquam sequi fugit incidunt reiciendis, mollitia quos?
      card_href: https://www.emmbl.de
