title: vf-tree
label: vf-tree
status: alpha

context:
  component-type: block
  tree_example_href: 'JavaScript:Void(0);'

  vf_tree_list:
    - title: Course Overview
      exapndable: false
    - title: What is bioinformatics?
      exapndable: true
    - title: The role of public databases
      exapndable: true
    - title: What makes a good bioinformatics database?
      exapndable: true
    - title: Tips on managing and sharing data?
      exapndable: true
    - title: Where do I submit my data?
      exapndable: true
    - title: Using ontologies to provide controlled vocabularies
      exapndable: true
    - title: Summary
      exapndable: true
    - title: Get help and support
      exapndable: true
