title: vf-tree
label: vf-tree
status: alpha

context:
  component-type: block
  tree_example_href: 'JavaScript:Void(0);'

  vf_tree_list:
    - title: Course Overview
      exapndable: false
    - title: What is bioinformatics?
      exapndable: true
    - title: The role of public databases
      exapndable: true
    - title: What makes a good bioinformatics database?
      expanded: true
      current-parent: true
      exapndable: true
      sublist:
        - title: Primary and secondary databases
        - title: Describing data consistently
        - title: Minimum information standards
        - title: Controlled vocabularies
          sublist:
            - title: Non-heirarchial list
              expanded: true
              current-child: true
            - title: Taxonomy
            - title: Thesaurus
            - title: Gene Ontology
    - title: Tips on managing and sharing data?
      exapndable: true
    - title: Where do I submit my data?
      exapndable: true
    - title: Using ontologies to provide controlled vocabularies
      exapndable: true
    - title: Summary
      exapndable: true
    - title: Get help and support
      exapndable: true
