# The title shown on the component page
title: vf-hero
# Label shown on index pages
label: vf-hero
status: alpha
# The template used from /components/_previews
#
# Per-variant options
# variants:
  # - name: default
  #   hidden: true
context:
  component-type: container

  vf_hero_link: https://example.com/
  vf_hero_text: The Hentze group combines biochemical and systems–level approaches to investigate the connections between gene expression and cell metabolism, and their roles in human disease.
  vf_hero_link-text: Learn more.

  vf_hero_heading: About the Hentze group
